### ISSUE TITLE
Update cx-portal-shared-components and Test Functionality

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk-frontend#21]
Product Name: [vas-country-risk-frontend](https://github.com/eclipse-tractusx/vas-country-risk-frontend)

### Description
This issue is about updating the `cx-portal-shared-components` to the latest stable release. After the update, the functionality of the dashboard should be tested to ensure that it still works correctly. If the updated library includes new functionality, the application should be updated accordingly. 

The update should not be performed if it results in the removal of any functionalities. 

After the update and testing, the Jest unit tests should be rewritten to reflect the updates.

### Tasks
- [ ] Update `cx-portal-shared-components` to the latest stable release
- [ ] Test the functionality of the dashboard and ensure that it still works correctly
- [ ] Update the application to incorporate any new functionality from the updated library
- [ ] Do not update if the new version of the library removes any functionalities
- [ ] Rewrite the Jest unit tests to reflect the updates

### Hints
Please be careful when updating libraries, as this can sometimes cause issues with existing code. Make sure to thoroughly test the application after updating the library.
Please use locally all apps you may need to test (backend, postgres, frontend)

### Information Sharing
Please update this issue with your progress as you work on these tasks. If you encounter any problems or have any questions, feel free to add comments to this issue.
